export const users = [
  {
    id: "1",
    name: "Thabo",
    surname: "Mbeki",
    email: "thabo.mbeki@example.com",
    idType: "ID",
    phone: "+27 71 234 5678",
    status: "Active",
    balance: 1250.75,
    walletStatus: "Active",
    walletCreated: "2023-05-12",
    twoFactorEnabled: false,
  },
  {
    id: "2",
    name: "Nomzamo",
    surname: "Mbatha",
    email: "nomzamo.mbatha@example.com",
    idType: "Passport",
    phone: "+27 82 345 6789",
    status: "Active",
    balance: 3450.5,
    walletStatus: "Active",
    walletCreated: "2023-06-18",
    twoFactorEnabled: true,
  },
  {
    id: "3",
    name: "Siya",
    surname: "Kolisi",
    email: "siya.kolisi@example.com",
    idType: "ID",
    phone: "+27 63 456 7890",
    status: "Active",
    balance: 5678.25,
    walletStatus: "Active",
    walletCreated: "2023-04-30",
    twoFactorEnabled: false,
  },
  {
    id: "4",
    name: "Bonang",
    surname: "Matheba",
    email: "bonang.matheba@example.com",
    idType: "ID",
    phone: "+27 74 567 8901",
    status: "Pending",
    balance: 0.0,
    walletStatus: "Pending",
    walletCreated: "2023-08-05",
    twoFactorEnabled: false,
  },
  {
    id: "5",
    name: "Trevor",
    surname: "Noah",
    email: "trevor.noah@example.com",
    idType: "Passport",
    phone: "+27 85 678 9012",
    status: "Active",
    balance: 12500.0,
    walletStatus: "Active",
    walletCreated: "2023-02-14",
    twoFactorEnabled: true,
  },
];
